### ISSUE TITLE
Update technical documentation for CBSS

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#101]
We will need to update the technical documentation page for the bibliography (currently here: https://dev-syriacaorg.vuexistapps.us/cbss/documentation.html).

**Comment by davidamichelson** [comment]
@wsalesky could you please have https://dev-syriacaorg.vuexistapps.us/cbss/documentation.html now display the text found here: https://github.com/srophe/syriaca-data/wiki/Comprehensive-Bibliography-on-Syriac-Studies (using however you do this with other wiki pages?)

Thanks

**Comment by wsalesky** [comment]
Updated here: https://github.com/srophe/syriaca/pull/126
