### ISSUE TITLE
CBSS Advanced Search option updates

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#102]
For the Advanced Search (https://dev-syriacaorg.vuexistapps.us/cbss/search.html), based on discussions on 2023-12-05, we would like the following advanced search options:

- [x] #108
    - Pulled into `/TEI/text/body/biblStruct///textLang/@mainLang`, example: https://dev-syriacaorg.vuexistapps.us/bibl/YHAZ3RFL
    - What do we do with records that do not have a `textLang/@mainLang`?
- [x] #109
- [x] #110
     - `/TEI/text/body/listRelation/relation[@type="subject"]/desc/text()`
- [x] #111
     - `/TEI/text/body/biblStruct/@type`
- [x] #112
    - Abstract is in `/TEI/text/body/biblStruct/note[@type="abstract"]/text()`

**Comment by wsalesky** [comment]
@wlpotter Are there abstracts in the bibl records? Coded as tei:abstract or tei:note?

**Comment by wlpotter** [comment]
There are some in the Zotero records, but I don't think that any of the subset we transformed for the demo included abstracts

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson  This will need to wait until the data is in the TEI records. Is there anything I need to do to get all the correct info from Zotero to the TEI?

**Comment by wlpotter** [comment]
@wsalesky I updated the initial comment with the xpaths for all this data based on the updated TEI from zot2bibl transform

**Comment by wsalesky** [comment]
@wlpotter When you say filter by, do you mean a facet or a dropdown menu in the advanced search? or both?

**Comment by wlpotter** [comment]
@wsalesky Sorry! I got some clarification on these yesterday but didn't have a chance to update the issues...I will add more specifics to the sub-issues now

**Comment by wsalesky** [comment]
I think these are all done. I will rebuild dev tonight and they can be tested
