### ISSUE TITLE
Update list of keyboards to use in the pop-up keyboard

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#103]
@wsalesky can we add these to the options for the virtual keyboard?

- Hebrew
- Russian
- Greek

For reference these are all installed for [Caesarea](https://caesarea-maritima.org/testimonia/browse.html)

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Just to be clear, this is just for the CBSS module correct? Or for all of syriaca.org?

**Comment by wlpotter** [comment]
Let's change this for all of syriaca.org

**Comment by wsalesky** [comment]
@wlpotter Great! That is actually easier, I did not build it for a module level (but I could if we needed it).

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/syriaca/pull/124 (will be in next update)
