### ISSUE TITLE
Add carousel image for CBSS

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#104]
Here was a suggestion from our 2023-12-05 meeting: https://upload.wikimedia.org/wikipedia/commons/b/b1/Rabbula_Gospels_%289v_%26_10r%3B_Four_Evangelists%29.jpg

Note: the uploader to wikimedia claimed it is public domain (cf. https://commons.wikimedia.org/wiki/File:Rabbula_Gospels_(9v_%26_10r;_Four_Evangelists).jpg), but the source is from https://dss-syriacpatriarchate.org/syriac-arts/syriac-icons/rabbula-gospels/?lang=en. It might be worth getting permission as the image may still be in copyright even though the Rabbula Gospels itself is not.

**Comment by dlschwartz** [comment]
Cropping an appropriate shape out of this piece of the image is what I actually had in mind. It might be easier for Winona to pass this along instead of the larger image. Also listed on wikimedia commons as public domain.

https://commons.wikimedia.org/wiki/File:St._John_the_Evangelist_(Rabbula_Gospels).png

**Comment by davidamichelson** [comment]
@wsalesky Here is the image we would like to use:
http://teca.bmlonline.it/ImageViewer/servlet/ImageViewer?idr=TECA0000025986&azione=showImg&sequence=30&reduce=1.9668367346938775&rotate=0&mode=1&height=751

Please crop it down to just the figure on the right to fit the size you need for carousel.

![Screenshot 2023-12-15 at 1 49 32 PM](https://github.com/srophe/syriaca/assets/3083773/deca72ab-c5bc-4410-a2ff-119d0aa3fc70)

One change, the carousel image itself needs a "Photo Credit" pop up (we actually need to add this for all carrousel images).

Please have text at the bottom left of the image that says "Photo Credit" and then when hovered over it should say:

Photo Credit: "John the Evangelist." Florence, Biblioteca Mediceo Laurenziana, cod. Plut. I, 56, f. 9b. Source: http://teca.bmlonline.it Used with permission for non-commerical purposes ["Copyright 2009 Ministero per i Beni e le Attività Cultura, ora Ministero dei beni e delle attività culturali e del turismo – Biblioteca Medicea Laurenziana
Tutti i diritti riservati. I contenuti del sito - codice di script, grafica, testi, tabelle, immagini, suoni, e ogni altra informazione disponibile in qualunque forma - sono protetti ai sensi della normativa vigente in tema di opere dell'ingegno. I prodotti software e i contenuti informativi, salvo diverse specifiche indicazioni, possono essere scaricati o utilizzati solo per uso personale, o comunque non commerciale citando la fonte (http://teca.bmlonline.it). Per usi diversi (lucro, commerciale) è consentito utilizzare, copiare e distribuire i documenti e le relative immagini disponibili su questo sito solo dietro permesso scritto da parte della Biblioteca Medicea Laurenziana. Le note di copyright, gli autori ove indicati o la fonte stessa devono in tutti i casi essere citati nelle pubblicazioni in qualunque forma realizzate e diffuse."].
