### ISSUE TITLE
CBSS record view on Browse and Search results pages

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#106]
Based on 2023-12-05 meeting, we will want to rework how results are displayed on browse (and search?).

Displaying portions of the abstract was mentioned. Including also the keyword tags.

Having a way to link immediately to DOIs or other URLs

**Comment by wlpotter** [comment]
Here is a mockup of what browse and search results should look like for each record (example record is https://dev.syriaca.org/bibl/6STTP2LD ):

Luise Abramowski, "Dadisho Qatraya and his Commentary on the Book of the Abbas Isaiah."The Harp vol. 4 (1991). {COPY CITATION BUTTON}
**URI**:  http://syriaca.org/cbss/6STTP2LD
Keywords: Abba Isaiah; asceticism; commentary; Dadisho Qatraya; exegesis; hagiography; Holy Spirit; hymnography; Nestorians; Theodore of Mopsuestia; VII CE; VII-XVIII CE

- for the citation, could we use the CMOS bibliography citation we get back from the Zotero data? currently these are stored in `/TEI/text/body/bibl[@type="formatted][@subtype="bibliography"]`
- Could the `{COPY CITATION BUTTON}` function similarly to the copy record title & URI to clipboard button we have currently, except that it copies the formatted citation instead?
- The URI is the bibl URI for the record, `/TEI/text/body/biblStruct/analytic/idno[@type="URI"]` that has the `http://syriaca.org/cbss/` URI base
- This example record does not have these, but ideally we would have links to Archive.org, DOIs, or other URLs display with a small icon based on the URL base
    - These are in `/TEI/text/body/biblStruct/analytic/ref/@target`
- The list of keywords should be displayed but link to faceted browse for each individual keyword (cf. #113). These should display in alphabetical order

**Comment by davidamichelson** [comment]
Luise Abramowski, "Dadisho Qatraya and his Commentary on the Book of the Abbas Isaiah."The Harp vol. 4 (1991): 67-83.
[URI: http://syriaca.org/cbss/6STTP2LD]

**Comment by wsalesky** [comment]
fixed
