### ISSUE TITLE
Filter by Language of Publication

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#108]

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter These are the values in `tei:textLang/@mainLang`

- eng
- ger
- Arabic
- la
- lat
- Hebrew
- English

Do you want to run a find and replace to regularize these?

**Comment by wsalesky** [comment]
@davidamichelson Waiting for an answer on this before I can wrap up these issues

**Comment by wlpotter** [comment]
@wsalesky we decided to cancel this one as most of the records don't have this data recorded in the Zotero records
