### ISSUE TITLE
Update label of the "Keyword search" box to be "Search All" (avoids confusion with searching by keyword/tag)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#109]
@wsalesky On the Advanced Search page

- [ ] Please change "Keyword:" to "Search All Fields:"
- [ ] Delete the light grey "Any word in citation" (leave this field blank)

![Screenshot 2023-12-15 at 1 32 49 PM](https://github.com/srophe/syriaca/assets/3083773/dc6a1e66-927b-417a-90fe-e729a382aa6a)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/syriaca/pull/130
