### ISSUE TITLE
Facet search results by Subject Keywords (tags)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#110]

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter I assume this is a facet? It would make a very long drop down menu on the search page. Or do you want to be able to search keywords?

**Comment by wlpotter** [comment]
@wsalesky For this one, I think we'd like to have these appear in two ways:

1. As a search box below the "Search all" box (that searches across all fields).
    - This box would be labelled "Search by Subject Keyword"
    - Users could search keywords, and the box would auto-suggest
    - We wonder if this box could function similarly to the recipient line for emails, where users can select an auto-suggested keyword that gets added to the search, and users could then search for another and add it to the search as well
    - Multiple keywords should filter results by "AND" facets, i.e. results should include both/all of the selected keywords
2. On the search results page, as a list in the side from which users can select keywords to further narrow down their search results (similar to how "Script" works in the BL search: https://bl.syriac.uk/search.html?keyword=ephraim vs https://bl.syriac.uk/search.html?facet-script=syr-Syre&keyword=ephraim)
    - Keywords should filter results as "AND" facets here as well
    - This function should work the same way as this facet on browse (cf. #113 )

Let us know how this sounds and we can discuss further the feasibility, etc.

**Comment by wsalesky** [comment]
Test on dev server. Close if works as expected

**Comment by wlpotter** [comment]
The facets on search results look to be working, but I'm getting an error with the "Search by Subject Keyword" field:

https://dev.syriaca.org/cbss/search.html?q=&keywordSearch=ephrem&title=&author=&pub-place=&publisher=&date=&abstract=&thesisLimit=true&idno=

**Comment by wlpotter** [comment]
This looks to be working now
