### ISSUE TITLE
"Search in" feature for Publication Type (book, article, dissertation, book chapter, etc.) in advanced search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#111]

**Comment by davidamichelson** [comment]
First we need to add publication type to the TEI

**Comment by wsalesky** [comment]
Added. Close if it works as expected

**Comment by wlpotter** [comment]
@wsalesky I don't think these are working yet; searching for the keyword "ephrem" yields 59 results, both with all search in boxes checked or not. Compare:

All boxes checked, 59 results: https://dev.syriaca.org/cbss/search.html?q=ephrem&keywordSearch=&title=&author=&pub-place=&publisher=&date=&abstract=&bookLimit=true&journalArticleLimit=true&bookSectionLimit=true&thesisLimit=true&idno= 

vs. only the "Thesis" box checked, also 59 results: https://dev.syriaca.org/cbss/search.html?q=ephrem&keywordSearch=&title=&author=&pub-place=&publisher=&date=&abstract=&thesisLimit=true&idno=

**Comment by wsalesky** [comment]
@wlpotter please recheck

**Comment by wlpotter** [comment]
Yes, this is working now
