### ISSUE TITLE
Faceted browse by Subject Keyword

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#113]
Waiting on zot2bibl update to grab keywords from Zotero tags

**Comment by wsalesky** [comment]
@wlpotter work in process. Trying to get 'AND' working on facets

**Comment by wlpotter** [comment]
@wsalesky these seem to be working (but likely as 'or'?) on the search results, but not on browse: https://dev.syriaca.org/cbss/browse.html?view=A-Z.

One thing we forgot to discuss on this in our meeting is if there's a way to let users search in the facet box while on browse (see the image example from Zotero for a comparable feature). The list of subjects is really long (see https://dev.syriaca.org/cbss/search.html?keyword=ephrem# for example), so any way to help users narrow down the subject list they want to find would be useful!

**Comment by wsalesky** [comment]
fixed. no search box, no and. will wait until the next iteration of the site.
