### ISSUE TITLE
Remove order by title

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#115]
No longer need to have a browse sort-by/order-by title. Note that this is the current default, but we want the default to instead rely on surname of author/creator (#114 )

**Comment by wsalesky** [comment]
@wlpotter Is this different from #114? If not, it is done. If it is different, I think I need more explanation?

**Comment by wlpotter** [comment]
I think it's basically same as #114, but we also want to remove the option of sorting by title entirely
