### ISSUE TITLE
Date slider to browse by creation date

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#116]

**Comment by wlpotter** [comment]
@wsalesky I believe the data for publication dates is in `/TEI/text/body/biblStruct/monogr/imprint/date`, but I'm only getting about 1,000 results when I search...Do you know if this data might be stored elsewhere in bibl records?

**Comment by wsalesky** [comment]
@wlpotter That is where they should be, according to the zotero2bibl transformation: $rec?data?date maps to imprint/date. If there is another place in Zotero where dates are stored they may have been missed.

**Comment by wlpotter** [comment]
There must be since most of the 20k+ records have dates. I'll take a closer look at the Zotero data to see if I can find where these are stored

**Comment by wlpotter** [comment]
Okay, solved part of this problem -- looks like we only have 1,008 TEI records here. I will double check the branches and see if I forgot to pull in the rest of the records

**Comment by wsalesky** [comment]
@wlpotter How many should there be?

**Comment by wsalesky** [comment]
Test on dev

**Comment by wlpotter** [comment]
Hmm I'm not getting narrower results when adjusting the sliders.

Compare: https://dev.syriaca.org/cbss/search.html?q=Zingerle&keywordSearch=&title=&author=&pub-place=&publisher=&date=&abstract=&bookLimit=true&journalArticleLimit=true&bookSectionLimit=true&thesisLimit=true&idno=

with 

https://dev.syriaca.org/cbss/search.html?startDate=1853-01-01&endDate=1856-02-23&thesisLimit=true&journalArticleLimit=true&bookLimit=true&q=Zingerle&bookSectionLimit=true

(adjusting end date to 1856 should remove at least one result that was published in 1857)

**Comment by wlpotter** [comment]
@wsalesky a few things here still:

- I think this facet only appears on search results, not on browse (https://dev.syriaca.org/cbss/search.html?keyword=ephrem but not on https://dev.syriaca.org/cbss/browse.html?view=A-Z)
- I wonder if there's an outlier date since the range 1827 - 2019 (see [this search](https://dev.syriaca.org/cbss/browse.html?view=A-Z)) is scrunched to the right? Or does the app set start and end date limits?
- Adjusting the date slider throws an error: https://dev.syriaca.org/cbss/search.html?startDate=1827-01-01&endDate=1950-05-03&keyword=ephrem

**Comment by wlpotter** [comment]
fwiw on the question of the date slider being scrunched up, the earliest dated record we have is 1555 CE

**Comment by wsalesky** [comment]
Fixed
