### ISSUE TITLE
Display of notes

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriaca#133]
The John of Ephesus records are currently showing `<note type="abstract">` as both an abstract just under the headword/URI and as a note in the "Descriptions" section. We want each note to appear only once.

We are also now allowing multiple abstracts for when a single record is a part of multiple series. One abstract might apply to multiple series or each series may have it's own. We designate the series to which an abstract corresponds using a `@corresp` attribute, the value of which matches the URI for the series as stated in the tei:seriesStmt in the header. The following should apply to the display of notes that have a `@type` attribute indicating and abstract:
- each note should appear only once
- if a note is an abstract for the view of the current series (Syriaca or John of Ephesus), it should appear just below the headword/URI.
- if there are multiple abstracts, the Syriaca view should show the John of Ephesus abstract (`<note type="abstract" corresp="http://syriaca.org/johnofephesus/persons">`) as a simple note displayed under "Descriptions"; and vice versa.

**Comment by wsalesky** [comment]
Updated.
