### ISSUE TITLE
Text for https://dev-syriacaorg.vuexistapps.us/johnofephesus/index.html

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#138]
Please update prose on https://dev-syriacaorg.vuexistapps.us/johnofephesus/index.html

This research portal aims to facilitate the study of the Ecclesiastical History of John of Ephesus by providing an open-access database which contains information on all the persons and places occurring in its third part, the only part of the work that has been preserved mostly intact. John (507–c. 589) was a prolific author and leader of the nascent miaphysite movement. His major works, all written in Syriac, include a collection of hagiographies known as the Lives of the Eastern Saints and an extensive Ecclesiastical History. The third part of the Ecclesiastical History covers events of the 570s and the 580s with a focus on Constantinople, but it also contains a wealth of information on other parts of the Roman Empire, Armenia, Persia, and Nubia from the perspective of a religious group repeatedly subjected to persecution. At present, this database is solely focused on the extant third part of John’s Ecclesiastical History; the fragments of the second part that can be retrieved from later Syriac chronicles have not been taken into account.

A Guide to John of Ephesus is part of the broader project [“Commentary on John of Ephesus’s Ecclesiastical History”](https://www.goethe-university-frankfurt.de/132206613/Commentary_on_John_of_Ephesus__Ecclesiastical_History) that has been ongoing since 2022 at the University of Frankfurt and KU Leuven (PIs Hartmut Leppin and Philip Forness). This project, generously funded by the DFG (German Research Foundation), aims to establish a new critical edition, translation, and comprehensive commentary on the third part of the Ecclesiastical History, integrating historical, philological, and theological research. In addition to the print versions scheduled to be published at the end of the project in 2031, the results of the research will gradually be made available online as the project progresses. The project collaborates with several digital humanities partners which host open-access versions of different parts of the project’s output. Apart from A Guide to John of Ephesus on syriaca.org, these are: (1) the [Patristic Text Archive](https://pta.bbaw.de/en/) which hosts the new critical edition, translation, and commentary; (2) the [Digital Syriac Corpus](https://syriaccorpus.org) which hosts a mirror version of the new critical edition.

**Comment by davidamichelson** [comment]
Also this text replaces both John of Ephesus and About:

John of Ephesus

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

About the project

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by wsalesky** [comment]
https://github.com/srophe/syriaca/pull/142
