### ISSUE TITLE
Update copy text for Prosopography to John of Ephesus, http://syriaca.org/johnofephesus/persons

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#139]
Dev address: https://dev-syriacaorg.vuexistapps.us/johnofephesus/persons/index.html

Please add the following copy text.

Title in banner image: "Part I: A Prosopography to John of Ephesus"
- note: current = "Prosopography to John of Ephesus’s _Ecclesiastical History_"

Sub-title in banner image: "This database contains prosopographical information on all persons mentioned in the third part of John of Ephesus’s _Ecclesiastical History_."
- note: current = "Tagline"

Sub-Module About Text: "_A Prosopography to John of Ephesus_ forms the first volume of _A Guide to John of Ephesus_ and contains a comprehensive catalogue of all the persons mentioned in the third part of the _Ecclesiastical History_, including persons who are only named once or to whom John refers only anonymously. For every figure, it provides the most important biographical data and a short description of the role they play in the _Ecclesiastical History_. It also lists all the chapters of the _Ecclesiastical History_ in which a person occurs and points to further bibliographic references."
- note: current = Lorem ipsum under the "About" heading, opposite banner image

**Comment by wsalesky** [comment]
https://github.com/srophe/syriaca/pull/142
