### ISSUE TITLE
Update copy text for Gazetteer to John of Ephesus

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#141]
Dev site: https://dev-syriacaorg.vuexistapps.us/johnofephesus/places/index.html

Please add the following copy text.

Title in banner image: "Part II: A Gazetteer to John of Ephesus"
- note: current = "Gazetteer to John of Ephesus’s _Ecclesiastical History_"

Sub-title in banner image: "This database contains information on all the places mentioned in the third part of John of Ephesus’s _Ecclesiastical History_."
- note: current = "Tagline"

Sub-Module About Text: "_A Gazetteer to John of Ephesus_ is the second volume of _A Guide to John of Ephesus_ and catalogues all the toponyms that occur in the third part of the _Ecclesiastical History_. It provides information on the exact location of these places, including a set of precise geographical coordinates, whenever they are known. But it also includes places John mentions without giving their exact name; in these cases, possible identifications are offered. Moreover, it briefly describes the significance of these places in the context of the _Ecclesiastical History_, lists the chapters where they are named, and gives short bibliographic references for further reading."
- note: current = Lorem ipsum under the "About" heading, opposite banner image

**Comment by wsalesky** [comment]
See: https://github.com/srophe/syriaca/pull/142
