### ISSUE TITLE
JoE basic search in Prosopography is searching all persons records

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#159]
The basic keyword search bar in the John of Ephesus persons modules is searching all of persons.

Persons example: https://dev-syriacaorg.vuexistapps.us/johnofephesus/persons/search.html?keyword=constantine includes https://dev-syriacaorg.vuexistapps.us/person/1655 which is not a JoE record. Should include only https://dev-syriacaorg.vuexistapps.us/johnofephesus/persons/5242 in the results list

Places appears to be working correctly (compare JoE search https://dev-syriacaorg.vuexistapps.us/johnofephesus/places/search.html?keyword=antioch with TSG search https://dev-syriacaorg.vuexistapps.us/geo/search.html?keyword=antioch)

**Comment by wsalesky** [comment]
fixed here: https://github.com/srophe/syriaca/pull/165
