### ISSUE TITLE
JoE Places Advanced Search

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#161]
Please remove the following from the JoE Places Advanced search page (https://dev-syriacaorg.vuexistapps.us/johnofephesus/places/search.html)

- Events (and associated date box)
- Attestations (and associated date box)
- Religious communities (and associated date box)
- Existence dates
- Related persons
- Related works

Additionally, I am not sure how the list of place types is generated (is it based on indexing the data or a predetermined list?). If it is pre-determined, could you please remove the following values: "diocese", "madrasa", "mosque", "parish", "synagogue", and "temple" as they are not used in the JoE places dataset.

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/syriaca/pull/163
