### ISSUE TITLE
CBSS Item pages should display subject keywords with links to faceted browse

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#177]
On item pages for CBSS we want to display the list of subject keywords, each of which links to a faceted browse by that keyword.

This would appear in a right-hand column of the record page (under where there is currently the "Relationships" heading).

Data is here: `/TEI/text/body/listRelation/relation[@ref="dc:subject"]/desc`. These would link to a browse faceted by that keyword, e.g. [Barhebraeus](https://dev.syriaca.org/cbss/browse.html?facet-cbssKeywords=Barhebraeus)

We would like to label this list as "Subject Keywords"

Example record: https://dev.syriaca.org/bibl/F5EH8BGS

**Comment by wsalesky** [comment]
Done
