### ISSUE TITLE
The editor @role="creator"

### ISSUE THREAD

**Issue by wsalesky** [srophe/syriaca#185]
The editor @role="creator" of all CBSS records looks like the following: 
```
<editor role="creator" ref="https://www.zotero.org/cbsc_admin">cbsc_admin</editor>
                <respStmt>
                    <resp>Record added to Zotero by</resp>
                    <name ref="https://www.zotero.org/cbsc_admin">cbsc_admin</name>
                </respStmt>
```

It then shows up in the citation as cbsc_admin. Where do we want to change this? In the data or the app, and what should it be changed to?

**Comment by davidamichelson** [comment]
Thanks @wsalesky, please keep the data as is. In the HTML, please just delete this entire section:

```

About this Online Entry
Additional Credit:

    Record added to Zotero by cbsc_admin

```

**Comment by wsalesky** [comment]
Done
