### ISSUE TITLE
Changes to CBSS Advanced Search: https://dev.syriaca.org/cbss/search.html

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#198]
@wsalesky Please make the following changes:

- [x] Remove all hints from all of the search boxes such as "Title of article, journal..."
- [x] In the "Search In:" check boxes, please change “Journal Articles” to “Journal Articles or Reviews”
- [x] Remove the Id Number search label and box (we no longer need this feature), also remove the horizontal line dividing this box from the other boxes.
- [x] When one first comes to the Advanced Search page, it displays "Sort/New" buttons at the bottom even though there are not yet any results. See image. Can these be deleted? 
![Delete sort:new](https://github.com/user-attachments/assets/847d8a72-4c3c-4ae4-8727-e90064784611)

**Comment by wsalesky** [comment]
fixed
