### ISSUE TITLE
On results page in CBSS the date slider does not change the results page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#202]
Using these results: https://dev.syriaca.org/cbss/search.html?q=&keywordSearch=&title=&author=Brock&pub-place=&publisher=&date=&abstract=&bookLimit=true&journalArticleLimit=true&bookSectionLimit=true&thesisLimit=true&idno=

moving the date slider does not change which results are displayed.

**Comment by wsalesky** [comment]
fixed
