### ISSUE TITLE
Please restore the RSS feed from the blog to the Syriaca.org home page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#29]
See e-mail from 3/21/22

Thanks!

**Comment by wsalesky** [comment]
Done.

**Comment by davidamichelson** [comment]
@wsalesky On Firefox on a Mac, the RSS feed appears to be plain text and leaves in HTML escape characters.

Is there anyway to display HTML so that

- [ ] the links in the post are live
- [ ] the escape characters don't show

See image
![Screenshot](https://user-images.githubusercontent.com/3083773/159785761-afb4cf74-9ead-460e-af47-343b0e48188e.png)

**Comment by davidamichelson** [comment]
Please just provide title, date and read more. Don't include content.

**Comment by wsalesky** [comment]
fixed
