### ISSUE TITLE
Deprecated and redirect URIs causing cardinality error

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#4]
@wsalesky the app is currently throwing errors on records that have been merged. For example, https://syriaca.org/person/1955 which had data merged from the deprecated record https://syriaca.org/person/1954

I think this is caused by the fact that there are two `//publicationStmt/idno` elements? 

Cf. https://github.com/srophe/srophe-app-data/issues/909

**Comment by wsalesky** [comment]
Fixed
