### ISSUE TITLE
Clicking on a record from search and browse results in BHSE or NHSL causes a 404 error

### ISSUE THREAD

**Issue by wlpotter** [srophe/syriaca#46]
@wsalesky when browsing from BHSE or NHSL, the link to each record does not appear to be forming correctly.

So, from https://syriaca.org/bhse/browse.html the first record links to https://syriaca.org/bhse/record.html?doc=/db/apps/srophe-data/data/works/tei/829.xml rather than the expected https://syriaca.org/work/829

This is the same for searching, e.g. https://syriaca.org/bhse/search.html?q=severus gives results like https://syriaca.org/bhse/record.html?doc=/db/apps/srophe-data/data/works/tei/nhsl/tei/3144.xml

NHSL browse and search function in the same way as BHSE: e.g., https://syriaca.org/nhsl/search.html?q=severus gives results like https://syriaca.org/nhsl/record.html?doc=/db/apps/srophe-data/data/works/tei/nhsl/tei/3144.xml

Both SBD and the Gazetteer, and Bibls, appear to be working correctly.

FYI @davidamichelson @dlschwartz

**Comment by wsalesky** [comment]
Fixed. please test and close if it works for you.

**Comment by wlpotter** [comment]
Yes, this works. Thanks!
