### ISSUE TITLE
updating person and place indexes

### ISSUE THREAD

**Issue by dlschwartz** [srophe/syriaca#69]
@wsalesky the [person](https://github.com/srophe/syriaca/blob/main/documentation/indexes/persons.xml) and [place](https://github.com/srophe/syriaca/blob/main/documentation/indexes/places.xml) indexes are slightly out of date which throws some errors in the schema. Can you please update those whenever it's convenient.

Also, we should discuss a mechanism to keep these up to date as we add new entities.

**Comment by wsalesky** [comment]
@dlschwartz Updated. Please let me know if you have any issues. I will make a new issue to to create a periodic index update

**Comment by dlschwartz** [comment]
Thanks Winona!
