### ISSUE TITLE
Logo/Banner Image Brainstorming?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/syriaca#83]
@wsalesky I am wondering how we could make better use of the Logo/Banner Image above the centered search box here: https://dev-syriacaorg.vuexistapps.us/bibl/index.html

<img width="1273" alt="Screenshot 2023-11-28 at 11 54 23 AM" src="https://github.com/srophe/syriaca/assets/3083773/ea93e97f-62a9-4898-b8a9-2fa4afbbcd9a">

It made sense in its old location as part of https://csc.huji.ac.il, but here is seems to take up space. I also see the center has stopped using the logo version we have here.

I would love to have the banner have the text 
### Sergey Minov, General Editor 
(see issue #82)

but then the title of the module would occur twice since it is also in the menu bar.

Thoughts on how to use this space? We could also work to find a different image since I believe technically this one is from an [Armenian](https://www.deadicated.nl/?p=6194) church mosaic rather than Syriac.

**Comment by davidamichelson** [comment]
Just to be clear, if you want to work up a different mock up before our next meeting, please do so!

**Comment by wsalesky** [comment]
@davidamichelson What do you think about something fairly simple: 
<img width="1701" alt="Screenshot 2023-12-04 at 1 55 14 PM" src="https://github.com/srophe/syriaca/assets/1168206/8b1b7f9e-fcd6-46ea-ad72-f0bc04c22f94">


I would need to add in the navigation buttons, under the title, but this is fairly attractive and clean, and requires no picture.

**Comment by davidamichelson** [comment]
Looks great we can discuss tomorrow

**Comment by davidamichelson** [comment]
@wsalesky Please move ahead with this slimmer design. In addition, please move the "scallop shell" logo down below and put it between Hebrew U and Vanderbilt Libraries. Please add the words below it "Center for the Study of Christianity" had have it point to https://csc.huji.ac.il/ (so technically two logos will point here, but that is fine)

**Comment by wsalesky** [comment]
@davidamichelson What are we using for a logo for this module?

**Comment by davidamichelson** [comment]
@wsalesky I will provide this in issue #100 

Thanks!

**Comment by wsalesky** [comment]
Updated here: https://github.com/srophe/syriaca/pull/125
